### ISSUE TITLE
DiscoIPC doesn't clear stats for timestamps

### ISSUE THREAD

**Issue by An0n3m0us** [k3rn31p4nic/discoIPC#3]
I have a script for a game where timestamps are used to show how long is left in a match. I want to be able to reset/clear/hide the values so that timestamps don't show up in Discord when the game is in the main menu. I already have a condition for gameState, but I don't know what to set the timestamps to, to hide them.

For now, when the user is in the main menu I set the time values to `int(time.time())` (so that they are the same value) for both timestamps so that Discord shows `00:00 left`.

**Comment by iamtraction** [comment]
Have you tried setting `timestamp` to an empty dict (`{}`)?

**Comment by An0n3m0us** [comment]
I did that and it worked! Thanks!

**Comment by An0n3m0us** [comment]
What about setting strings to nothing? Like `state`? I tried:
`{}`, `[]`, `None`, `"None"`, `0`

**Comment by iamtraction** [comment]
Set it to empty string, `""`

**Comment by An0n3m0us** [comment]
I tried that too. It didn't work:
`activity['details'] = ""`
