### ISSUE TITLE
Exception: Can't send data to Discord via IPC.

### ISSUE THREAD

**Issue by Hefaustas** [k3rn31p4nic/discoIPC#5]
> File "C:\Python27\lib\site-packages\discoIPC\ipc.py", line 156, in update_activity
>     self._send(1, payload)
>   File "C:\Python27\lib\site-packages\discoIPC\ipc.py", line 95, in _send
>     raise Exception('Can\'t send data to Discord via IPC.')
> Exception: Can't send data to Discord via IPC.

I haven't been able to fix this issue yet.

**Comment by iamtraction** [comment]
Can you show a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by miameows** [comment]
Same issue. Just try to connect with client.connect, it doesn't work.

**Comment by Mineinjava** [comment]
I cannot reproduce.
Make sure that your client id is an actual client id (the one in the example is not valid)

**Comment by Hefaustas** [comment]
Sorry I forgot to close this, I fixed this recently and I think there was just something wrong with my client ID.
