### ISSUE TITLE
discoIPC is not connecting

### ISSUE THREAD

**Issue by An0n3m0us** [k3rn31p4nic/discoIPC#6]
It seems the module is not working, but I cannot determine why.
I tried with Python 2.7, 3.5 and 3.8 and I am on Ubuntu 16.04 (Linux).

Step to reproduce:
Download https://github.com/iamtraction/riddles-rich-presence and run the script
(Or just run any script that uses this module to connect to Discord)

No output is shown, and this error is dumped after Ctrl+C:
```
Traceback (most recent call last):
  File "riddles.py", line 90, in <module>
    main()
  File "riddles.py", line 27, in main
    client.connect()
  File "/home/$redacted$/.local/lib/python3.8/site-packages/discoIPC/ipc.py", line 119, in connect
    self._decode()
  File "/home/$redacted$/.local/lib/python3.8/site-packages/discoIPC/ipc.py", line 77, in _decode
    recived_data = self.socket.recv(1024)
KeyboardInterrupt
```

Using `trace`, I can see the code getting stuck at:
```
encoder.py(200):         if not isinstance(chunks, (list, tuple)):
encoder.py(202):         return ''.join(chunks)
ipc.py(56):         payload = payload.encode('utf-8')
ipc.py(57):         return struct.pack('<ii', opcode, len(payload)) + payload
ipc.py(88):         try:
ipc.py(89):             if self.platform == 'windows':
ipc.py(93):                 self.socket.send(encoded_payload)
ipc.py(119):             self._decode()
 --- modulename: ipc, funcname: _decode
ipc.py(61):         if self.platform == 'windows':
ipc.py(77):             recived_data = self.socket.recv(1024)
```

Any idea why this is occurring? It has been working fine for me for a very long time, so I'm sure that all my scripts that use the module are working okay.

**Comment by iamtraction** [comment]
> Download https://github.com/iamtraction/riddles-rich-presence and run the script

Are you setting the client ID in the config?


Here's an example code from one of my scripts that's using this library:
```py
from discoIPC import ipc
...
client = ipc.DiscordIPC(config["CLIENT"]["client_id"])
client.connect()
client.update_activity(get_stats())
```
and it's working fine:

![image](https://user-images.githubusercontent.com/19631364/111115643-ee01ab80-858a-11eb-8394-989874f6b136.png)


Could you show the part of the code that shows how you're using it?

**Comment by An0n3m0us** [comment]
> Are you setting the client ID in the config?

Yep. I've also tested with 4 other scripts that I have been using for a while.
Like this one:
https://github.com/An0n3m0us/DiscordRPBlender

They've all stopped working for me :/

> Could you show the part of the code that shows how you're using it?

I'm running the example code from the repository I mentioned in the original post, then I placed my client ID in the config file.

I know it should work, because I tested it like this when I first used the module.

EDIT:

Hmm, it seems not to be to do with this module.
I tested with this too, which usually works:
https://github.com/HelloWorld017/atom-discord

**Comment by iamtraction** [comment]
Is your Discord client installed via Snap?

**Comment by An0n3m0us** [comment]
No, via `apt` due to being on Ubuntu `16.04`.

**Comment by An0n3m0us** [comment]
Hmm, I restarted my device and it seems to work now.
Should've probably did that first, but I didn't expect that to have anything to do with it.

Thank you for your time, anyway.
